# Generated by Django 6.0.1 on 2026-03-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_section_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='capacity',
            field=models.PositiveIntegerField(default=40),
        ),
    ]
