# Generated by Django 6.0.3 on 2026-04-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teacher_profiles', to='accounts.subject'),
        ),
    ]
