# Generated by Django 6.0.3 on 2026-03-13 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(help_text='e.g. 2023-2024', max_length=12)),
                ('grade_level', models.IntegerField(help_text='0=Kinder, 1=Grade 1 … 6=Grade 6')),
                ('section_name', models.CharField(blank=True, max_length=100)),
                ('subject_name', models.CharField(max_length=150)),
                ('subject_code', models.CharField(blank=True, max_length=30)),
                ('q1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('q2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('q3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('q4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.CharField(blank=True, choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('PROMOTED', 'Promoted'), ('RETAINED', 'Retained'), ('INCOMPLETE', 'Incomplete')], max_length=20)),
                ('teacher_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_histories', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'PARENT_STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-school_year', 'subject_name'],
                'unique_together': {('student', 'school_year', 'subject_name')},
            },
        ),
    ]
