# Generated by Copilot on 2026-04-09

from django.db import migrations, models


def backfill_academic_record_names(apps, schema_editor):
    AcademicRecord = apps.get_model('grades', 'AcademicRecord')
    Enrollment = apps.get_model('enrollment', 'Enrollment')
    UserProfile = apps.get_model('accounts', 'UserProfile')

    for record in AcademicRecord.objects.select_related('student').all():
        student_name = (record.student_name or '').strip()
        student_number = (record.student_number or '').strip()

        if student_name and student_number:
            continue

        enrollment = (
            Enrollment.objects.filter(student_id=record.student_id, academic_year=record.school_year)
            .order_by('-created_at', '-id')
            .first()
        )

        if enrollment:
            if not student_name:
                student_name = f"{enrollment.first_name or ''} {enrollment.last_name or ''}".strip()
            if not student_number:
                student_number = (enrollment.student_number or '').strip()

        if not student_name:
            profile = UserProfile.objects.filter(user_id=record.student_id).first()
            if profile:
                student_name = f"{profile.student_first_name or ''} {profile.student_last_name or ''}".strip()
                if not student_number:
                    student_number = (profile.student_number or '').strip()

        if not student_name:
            student_name = getattr(record.student, 'username', '') or '—'

        AcademicRecord.objects.filter(pk=record.pk).update(
            student_name=student_name,
            student_number=student_number,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_alter_academicrecord_id_alter_classstanding_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicrecord',
            name='student_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='student_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.RunPython(backfill_academic_record_names, migrations.RunPython.noop),
    ]
