# Generated by Django 6.0.3 on 2026-03-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, default='123 School St., City, Country')),
                ('phone_number', models.CharField(blank=True, default='+1234567890', max_length=50)),
                ('email', models.EmailField(blank=True, default='info@school.edu', max_length=254)),
                ('facebook_link', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Contact & Inquiry',
            },
        ),
        migrations.CreateModel(
            name='MissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_text', models.TextField(blank=True, default='Our mission is to provide excellent education.')),
                ('vision_text', models.TextField(blank=True, default='Our vision is to be a leading educational institution.')),
            ],
            options={
                'verbose_name_plural': 'Mission & Vision',
            },
        ),
        migrations.CreateModel(
            name='SchoolInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Our School', max_length=255)),
                ('about_text', models.TextField(blank=True, default='Welcome to our school.')),
            ],
            options={
                'verbose_name_plural': 'School Information',
            },
        ),
    ]
