# Generated by Django 5.2.12 on 2026-04-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmodule', '0003_alter_contactinquiry_id_alter_missionvision_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinquiry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='missionvision',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schoolinformation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
