# Generated by Django 6.0.2 on 2026-03-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_key', models.CharField(choices=[('prek', 'Pre-Kinder'), ('kinder', 'Kinder'), ('grade1-3', 'Grade 1-3'), ('grade4-5', 'Grade 4-5'), ('grade6', 'Grade 6')], max_length=20, unique=True)),
                ('grade_label', models.CharField(max_length=100)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('installment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('initial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reservation_fee', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('misc_aug', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('misc_nov', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('assessment', models.DecimalField(decimal_places=2, default=300, max_digits=10)),
                ('total_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_installment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tuition Configuration',
                'verbose_name_plural': 'Tuition Configurations',
                'ordering': ['grade_key'],
            },
        ),
    ]
