# Generated by Django 6.0.2 on 2026-03-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_tuitionconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionconfig',
            name='grade_key',
            field=models.CharField(choices=[('prek', 'Pre-Kinder'), ('kinder', 'Kinder'), ('grade1', 'Grade 1'), ('grade2', 'Grade 2'), ('grade3', 'Grade 3'), ('grade4', 'Grade 4'), ('grade5', 'Grade 5'), ('grade6', 'Grade 6')], max_length=20, unique=True),
        ),
    ]
