# Generated by Django 6.0.2 on 2026-03-23 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['date_created', 'id']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_posted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='entry_type',
            field=models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], default='DEBIT', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='item',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('PAYMENT', 'Payment'), ('INITIAL', 'Initial Payment'), ('MONTHLY', 'Monthly Installment'), ('MISC', 'Miscellaneous'), ('RESERVATION', 'Reservation Fee'), ('ASSESSMENT', 'Assessment'), ('OTHER', 'Other')], default='PAYMENT', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='school_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='semester',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('PENDING', 'Pending'), ('OVERDUE', 'Overdue'), ('POSTED', 'Posted')], default='POSTED', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('TUITION', 'Tuition Fee'), ('MISC', 'Miscellaneous'), ('REGISTRATION', 'Registration Fee'), ('BOOKS', 'Books & Materials'), ('UNIFORM', 'Uniform'), ('OTHER', 'Other')], default='TUITION', max_length=20),
        ),
    ]
