# Generated by Django 6.0.2 on 2026-03-23 18:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_transaction_options_transaction_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
