# Generated by Django 6.0.3 on 2026-03-25 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_transaction_date_posted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofOfPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(help_text='Payment reference/transaction number from bank or payment provider', max_length=50)),
                ('payment_amount', models.DecimalField(decimal_places=2, help_text='Amount shown in the proof of payment', max_digits=10)),
                ('payment_date', models.DateField(help_text='Date the payment was made')),
                ('payment_method', models.CharField(help_text='Method of payment (e.g., Bank Transfer, GCash, Check)', max_length=50)),
                ('document', models.FileField(help_text='Upload image or PDF of payment proof (receipt, bank transfer confirmation, etc.)', upload_to='payment_proofs/%Y/%m/')),
                ('description', models.TextField(blank=True, help_text='Additional notes or details about the payment', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESUBMIT', 'Resubmit Required')], default='PENDING', help_text='Review status of the submitted proof', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if status is REJECTED', null=True)),
                ('submitted_date', models.DateTimeField(auto_now_add=True, help_text='When the proof was submitted')),
                ('reviewed_date', models.DateTimeField(blank=True, help_text='When the proof was reviewed', null=True)),
                ('parent', models.ForeignKey(help_text='The parent/student submitting the proof', limit_choices_to={'role': 'PARENT_STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this proof', limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payment_proofs', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(help_text='The transaction this proof is for', on_delete=django.db.models.deletion.CASCADE, related_name='proof_of_payment', to='finance.transaction')),
            ],
            options={
                'verbose_name': 'Proof of Payment',
                'verbose_name_plural': 'Proofs of Payment',
                'ordering': ['-submitted_date'],
            },
        ),
    ]
