# Generated by Django 6.0.2 on 2026-03-26 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0014_enrollmentdocument'),
        ('finance', '0007_proofofpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to='enrollment.enrollment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='grade_level_snapshot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_mode_snapshot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='student_number_snapshot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='student_type_snapshot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
