# Generated by Django 6.0.1 on 2026-03-27 17:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_transaction_enrollment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proofofpayment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='proofofpayment',
            name='document',
        ),
        migrations.RemoveField(
            model_name='proofofpayment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='proofofpayment',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='proofofpayment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='proofofpayment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='proofofpayment',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='proofofpayment',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='proofofpayment',
            name='reviewed_date',
        ),
        migrations.RemoveField(
            model_name='proofofpayment',
            name='submitted_date',
        ),
        migrations.RemoveField(
            model_name='proofofpayment',
            name='transaction',
        ),
        migrations.AddField(
            model_name='proofofpayment',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proofofpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proofofpayment',
            name='proof_image',
            field=models.ImageField(default='', upload_to='proofs/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proofofpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proofofpayment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proof_of_payments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proofofpayment',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proofofpayment',
            name='reference_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proofofpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
