# Generated by Django 6.0.1 on 2026-04-01 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0015_enrollment_id_image_data_and_more'),
        ('finance', '0009_alter_proofofpayment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofofpayment',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_proof', to='enrollment.enrollment'),
        ),
        migrations.AddField(
            model_name='proofofpayment',
            name='payment_type',
            field=models.CharField(choices=[('enrollment', 'Enrollment Initial Payment'), ('installment', 'Installment Payment')], default='installment', max_length=20),
        ),
        migrations.AddField(
            model_name='proofofpayment',
            name='source',
            field=models.CharField(blank=True, choices=[('enrollment_form', 'Enrollment Form'), ('student_portal', 'Student Portal')], max_length=50, null=True),
        ),
    ]
