# Generated by Django 6.0.2 on 2026-04-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_proofofpayment_enrollment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='item',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('PAYMENT', 'Payment'), ('INITIAL', 'Initial Payment'), ('MONTHLY', 'Monthly Installment'), ('MISC', 'Miscellaneous'), ('RESERVATION', 'Reservation Fee'), ('ASSESSMENT', 'Assessment'), ('REFUND', 'Refund'), ('ADVANCE', 'Advance Credit'), ('OTHER', 'Other')], default='PAYMENT', max_length=20),
        ),
    ]
