# Generated by Django 6.0.2 on 2026-04-02 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0016_enrollment_payment_method'),
        ('finance', '0011_alter_transaction_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='item',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('PAYMENT', 'Payment'), ('INITIAL', 'Initial Payment'), ('MONTHLY', 'Monthly Installment'), ('MISC', 'Miscellaneous'), ('RESERVATION', 'Reservation Fee'), ('ASSESSMENT', 'Assessment'), ('REFUND', 'Refund'), ('ADVANCE', 'Advance Credit'), ('ADVANCE_TRANSFER_OUT', 'Advance Transfer Out'), ('ADVANCE_APPLIED', 'Advance Applied'), ('OTHER', 'Other')], default='PAYMENT', max_length=20),
        ),
        migrations.CreateModel(
            name='AdvanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('APPLY_ADVANCE', 'Apply Advance'), ('REFUND', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSED', 'Processed')], default='PENDING', max_length=20)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_requests', to='enrollment.enrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
