# Generated by Django 6.0.3 on 2026-03-08 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('classmanagement', '0002_room_schoolyear_alter_schedule_room_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-date', 'student__username', 'schedule__start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='The specific class/subject period this attendance is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='classmanagement.schedule'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'date', 'schedule')},
        ),
    ]
