# Generated by Django 6.0.2 on 2026-04-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendancerecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('PRESENT', 'Present'),
                    ('ABSENT', 'Absent'),
                    ('LATE', 'Late'),
                    ('EXCUSED', 'Excused'),
                ],
                default='PRESENT',
                max_length=10,
                null=True,
            ),
        ),
    ]
