# Generated by Django 6.0.2 on 2026-03-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_alter_announcement_target_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementmedia',
            name='data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcementmedia',
            name='data_mime',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='announcementmedia',
            name='original_filename',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
