# Generated by Django 6.0.2 on 2026-04-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_reminder_event_type_reference_date_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='event_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
