"""
Django settings for CESI project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-fallback-dev-key')

# SECURITY WARNING: don't run with debug turned on in production!
# For testing in production_test branch, we keep True (dev/test). Set DJANGO_DEBUG=False in DigitalOcean when ready.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') != 'False'



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'announcements',
    'rest_framework',
    
    'rest_framework.authtoken',
    'corsheaders',
    'accounts',
    'enrollment',
    'finance',
    'grades',
    'attendance',
    'classmanagement',
    'messaging',
    'reminders',
    'cmsmodule',
]


# DRF defaults
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "CESI.authentication.CsrfExemptSessionAuthentication",
    ],
     "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
         "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "300/hour",         # general anonymous traffic (dev-friendly)
        "user": "2000/hour",        # authenticated users (avoid dashboard burst 429s)
        "enrollment_public": "5/hour",  # STRICT: public enrollment submit
    },
    
    # "DEFAULT_THROTTLE_RATES": {
    #     "anon": "1/min",
    #     "user": "1/min",
    #     "enrollment_public": "10/min",
    # },
}
# Email backend for development - prints emails to console
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# # FRONTEND_URL = "http://localhost:5173"  # or your real domain later

# # EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# # EMAIL_HOST = "smtp.gmail.com"
# # EMAIL_PORT = 587
# # EMAIL_USE_TLS = True
# # EMAIL_HOST_USER = "zekaido123@gmail.com"  # Your Gmail address
# # EMAIL_HOST_PASSWORD = "ZeckAkali002"  # Gmail App Password (not normal password)
# # DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# # EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# DEFAULT_FROM_EMAIL = "noreply@cesi.local"
# FRONTEND_URL = "http://localhost:5173"




# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# FRONTEND_URL = "http://localhost:5173"  # or your real domain later
# DEFAULT_FROM_EMAIL = "noreply@cesi.local"

# Email backend for production - configure with real SMTP server and credentials
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'cesi.support@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'placeholder-password')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# CORS settings for development - adjust for production as needed
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ADD THIS LINE HERE
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
] # dev only
ROOT_URLCONF = 'CESI.urls'
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "162.159.140.98",
    "172.66.0.96",
    "cesiportal-app-nypkd.ondigitalocean.app",
    "*",  # Temporary for testing; replace with specific hostname in production.
]
# CSRF / Session config for cross-origin dev
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
    "https://cesiportal-app-nypkd.ondigitalocean.app",
]
CORS_ALLOW_ALL_ORIGINS = False  # Set to False for production
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "https://cesiportal-app-nypkd.ondigitalocean.app",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "origin",
    "x-csrftoken",
    "x-requested-with",
]


# Allow session cookie to be sent on cross-origin requests (dev only)
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True




TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CESI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=False,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

AUTH_USER_MODEL = 'accounts.User'

#Announcements settings
import os
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")