# Generated by Django 6.0.3 on 2026-03-27 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_messagedeletionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRestrictionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LIFTED', 'Lifted'), ('APPLIED', 'Applied')], max_length=32)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restriction_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('restriction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='messaging.chatrestriction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
