# Generated by Django 6.0.3 on 2026-03-25 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_passwordresetrequest'),
        ('classmanagement', '0002_room_schoolyear_alter_schedule_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='accounts.subject'),
        ),
    ]
