# Generated by Django 6.0.2 on 2026-03-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0011_alter_enrollment_student_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateField(blank=True, help_text='Enrollment window start date. Leave blank to use auto default (June 1).', null=True)),
                ('window_days', models.PositiveIntegerField(default=7, help_text='Number of days the enrollment form is open.')),
                ('academic_year', models.CharField(blank=True, help_text='Current academic year, e.g. 2025-2026. Leave blank to auto-calculate.', max_length=9, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enrollment Settings',
                'verbose_name_plural': 'Enrollment Settings',
            },
        ),
    ]
