# Generated by Django 6.0.1 on 2026-03-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0012_enrollmentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to='enrollment_ids/'),
        ),
    ]
