# Generated by Django 6.0.2 on 2026-03-25 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0013_enrollment_id_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('form_137', 'Form 137-E'), ('sf10', 'School Form 10 (SF10)'), ('birth_certificate', 'Birth Certificate'), ('good_moral', 'Good Moral Certificate'), ('report_card', 'Report Card'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='enrollment_documents/')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='enrollment.enrollment')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
