# Generated by Django 6.0.2 on 2026-03-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0014_enrollmentdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='id_image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='id_image_filename',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='id_image_mime',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
