# Generated by Django 6.0 on 2026-04-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0015_enrollment_id_image_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('online', 'Online (Offsite)'), ('onsite', 'Onsite (In-person)')], max_length=20, null=True),
        ),
    ]
